# app/services/mock_dashboard.py

MOCK_DASHBOARD = {
    "games": [
        {
            "game_id": "401472839",
            "start_time": "2026-04-12T13:05:00Z",
            "home_team": "NYY",
            "away_team": "BOS",
            "stadium_hr_factor": 125,
            "pitchers": {
                "home_pitcher": {
                    "name": "Gerrit Cole",
                    "era": 2.45,
                    "whip": 1.02,
                    "hand": "R",
                },
                "away_pitcher": {
                    "name": "Chris Sale",
                    "era": 3.78,
                    "whip": 1.20,
                    "hand": "L",
                },
            },
            "hitters": {
                "away_top_hitters": [
                    {
                        "name": "Rafael Devers",
                        "bvp_hr": 1,
                        "bvp_hr_points": 2,
                        "bvp_avg": 0.295,
                        "bvp_avg_points": 3,
                        "streak": 5,
                        "streak_points": 5,
                        "ballpark_hr_factor": 125,
                        "ballpark_points": 4,
                        "raw_score": 14,
                        "hitter_score": 56,
                        "team": "BOS",
                        "opponent": "NYY",
                        "pitcher": "Gerrit Cole",
                    },
                    {
                        "name": "Justin Turner",
                        "bvp_hr": 0,
                        "bvp_hr_points": 0,
                        "bvp_avg": 0.26,
                        "bvp_avg_points": 2,
                        "streak": 3,
                        "streak_points": 3,
                        "ballpark_hr_factor": 125,
                        "ballpark_points": 4,
                        "raw_score": 9,
                        "hitter_score": 36,
                        "team": "BOS",
                        "opponent": "NYY",
                        "pitcher": "Gerrit Cole",
                    },
                ],
                "home_top_hitters": [
                    {
                        "name": "Aaron Judge",
                        "bvp_hr": 2,
                        "bvp_hr_points": 4,
                        "bvp_avg": 0.31,
                        "bvp_avg_points": 3,
                        "streak": 7,
                        "streak_points": 7,
                        "ballpark_hr_factor": 125,
                        "ballpark_points": 4,
                        "raw_score": 18,
                        "hitter_score": 72,
                        "team": "NYY",
                        "opponent": "BOS",
                        "pitcher": "Chris Sale",
                    },
                    {
                        "name": "Giancarlo Stanton",
                            "bvp_hr": 1,
                            "bvp_hr_points": 2,
                            "bvp_avg": 0.28,
                            "bvp_avg_points": 2,
                            "streak": 4,
                            "streak_points": 4,
                            "ballpark_hr_factor": 125,
                            "ballpark_points": 4,
                            "raw_score": 12,
                            "hitter_score": 48,
                            "team": "NYY",
                            "opponent": "BOS",
                            "pitcher": "Chris Sale",
                    },
                ],
            },
            "team_scores": {
                "home_offense_score": 78,
                "away_offense_score": 65,
                "combined_game_score": 143,
            },
        }
    ]
}
